server.port=8084
spring.application.name=lab-4-secured

spring.security.user.name=admin
spring.security.user.password=${ACTUATOR_PASSWORD:changeme}
spring.security.user.roles=ACTUATOR_ADMIN

management.server.port=9084
management.endpoints.web.exposure.include=health,info,sbom
